/* Jyothirmaye Jewellers storefront. Edit this fallback only if a product is not yet in the admin catalogue. */
const WHATSAPP_NUMBER = "919440030500";
const PRODUCT_KEY = "jyothirmayeProducts";
const SETTINGS_KEY = "jyothirmayeSettings";
const SHOP_NAME = "JYOTHIRMAYE JEWELLERS";
const SHOP_ADDRESS = "Lift Building, Gandhi Chowk, G.N. T. Road, Gannavaram, Andhra Pradesh 521101";
const SHOP_MAP_URL = "https://www.google.com/maps/search/?api=1&query=Lift+Building%2C+Gandhi+Chowk%2C+G.N.+T.+Road%2C+Gannavaram%2C+Andhra+Pradesh+521101";
const seedProducts = [
 {id:101,name:"Temple Bloom Necklace",category:"gold",type:"Necklace",description:"A statement temple-inspired necklace, finished with intricate motifs and a timeless heirloom feel.",weight:"24.8 g",price:"",huid:"Available",customisation:"Available",stock:"Available",image:"https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=85"},
 {id:102,name:"Heritage Gold Bangles",category:"gold",type:"Bangle",description:"Classic gold bangles with delicate detailing, made to accompany celebrations and everyday rituals.",weight:"18.2 g",price:"",huid:"Available",customisation:"Available",stock:"Available",image:"https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=800&q=85"},
 {id:103,name:"Lakshmi Kasu Earrings",category:"gold",type:"Earrings",description:"A graceful pair inspired by traditional kasu craft, lovingly finished for a festive glow.",weight:"8.4 g",price:"",huid:"Available",customisation:"Not Available",stock:"Available",image:"https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=85"},
 {id:104,name:"Everyday Gold Chain",category:"gold",type:"Chain",description:"A versatile, beautifully polished chain with a clean profile for layering or wearing alone.",weight:"10.1 g",price:"",huid:"Available",customisation:"Available",stock:"Available",image:"https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=85"},
 {id:105,name:"Antique Bridal Haaram",category:"gold",type:"Bridal",description:"A richly detailed bridal haaram crafted for the centrepiece moments of your wedding day.",weight:"42.6 g",price:"",huid:"Available",customisation:"Available",stock:"Available",image:"https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=85"},
 {id:106,name:"Petal Gold Pendant",category:"gold",type:"Pendant",description:"A delicate floral pendant with a soft, luminous finish. Ask us about a custom chain pairing.",weight:"5.6 g",price:"",huid:"Available",customisation:"Available",stock:"Available",image:"https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85"},
 {id:107,name:"Silver Anklet Pair",category:"silver",type:"Anklet",description:"Fine silver anklets with a gentle traditional jingle, designed for a comfortable fit.",weight:"26.0 g",price:"",huid:"Not Applicable",customisation:"Not Available",stock:"Available",image:"https://images.unsplash.com/photo-1619119069152-a2b331eb392a?auto=format&fit=crop&w=800&q=85"},
 {id:108,name:"Silver Pooja Diya",category:"silver",type:"Pooja Item",description:"A finely finished silver diya, a thoughtful companion for daily prayer and auspicious gifting.",weight:"32.5 g",price:"",huid:"Not Applicable",customisation:"Not Available",stock:"Available",image:"https://images.unsplash.com/photo-1627293509201-cd0c7800432e?auto=format&fit=crop&w=800&q=85"},
 {id:109,name:"Silver Classic Ring",category:"silver",type:"Ring",description:"A simple, elegant silver ring with a polished profile suited to every day.",weight:"6.3 g",price:"",huid:"Not Applicable",customisation:"Available",stock:"Available",image:"https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85"},
 {id:110,name:"Silver Gift Bowl",category:"silver",type:"Gift Article",description:"An elegant silver keepsake for weddings, housewarmings, and celebrations worth remembering.",weight:"48.0 g",price:"",huid:"Not Applicable",customisation:"Not Available",stock:"Available",image:"https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=800&q=85"}
];
const categoryNames={gold:["Necklace","Chain","Bangle","Earrings","Ring","Pendant","Bracelet","Mangalsutra","Nose Pins","Bridal","Kids","Custom"],silver:["Chain","Ring","Anklet","Bracelet","Earrings","Bangle","Pendant","Idol","Pooja Item","Gift Article","Utensils","Accessories"]};
const categoryLabels={gold:["Gold Necklaces","Gold Chains","Gold Bangles","Gold Earrings","Gold Rings","Gold Pendants","Gold Bracelets","Gold Mangalsutra","Gold Nose Pins","Bridal Gold Jewellery","Kids Gold Jewellery","Custom Gold Jewellery"],silver:["Silver Chains","Silver Rings","Silver Anklets","Silver Bracelets","Silver Earrings","Silver Bangles","Silver Pendants","Silver Idols","Silver Pooja Items","Silver Gift Articles","Silver Utensils","Silver Accessories"]};
let activeMetal="gold",activeCategory="All";
function getProducts(){try{const stored=JSON.parse(localStorage.getItem(PRODUCT_KEY));if(Array.isArray(stored))return stored;}catch{}localStorage.setItem(PRODUCT_KEY,JSON.stringify(seedProducts));return seedProducts;}
function getSettings(){let s={};try{s=JSON.parse(localStorage.getItem(SETTINGS_KEY))||{};}catch{}if(s.contactDefaultsVersion!==1){Object.assign(s,{shopName:SHOP_NAME,phone:"09440030500",whatsapp:WHATSAPP_NUMBER,address:SHOP_ADDRESS,mapsUrl:SHOP_MAP_URL,contactDefaultsVersion:1});try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(s));}catch{}}return s;}
function waNumber(){const s=getSettings();return String(s.whatsapp||WHATSAPP_NUMBER).replace(/\D/g,"");}
function whatsappLink(message){const n=waNumber();return `https://wa.me/${n}?text=${encodeURIComponent(message)}`;}
function recordEnquiry(product){try{const key="jyothirmayeEnquiries",items=JSON.parse(localStorage.getItem(key)||"[]");items.unshift({name:"",phone:"",product:product||"General enquiry",date:new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date()),status:"New"});localStorage.setItem(key,JSON.stringify(items));}catch{}}
function orderMessage(p){return `Hello Jyothirmaye Jewellers,\n\nI am interested in this jewellery.\n\nProduct: ${p.name}\nCategory: ${p.category[0].toUpperCase()+p.category.slice(1)}\nWeight: ${p.weight||"Please share"}\nHUID: ${p.huid||"Please confirm"}\nCustomisation: ${p.customisation||"Please confirm"}\nPrice: ${p.price||"Price on Request"}\n\nPlease share more details.\n\nThank you.`;}
function escapeHtml(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function matchesCategory(p){if(activeCategory==="All")return true;return (p.type||"").toLowerCase().includes(activeCategory.toLowerCase())||p.name.toLowerCase().includes(activeCategory.toLowerCase());}
function renderPills(){const box=document.getElementById("categoryPills");const labels=categoryLabels[activeMetal];box.innerHTML=["All",...labels].map((label,i)=>{const key=i===0?"All":categoryNames[activeMetal][i-1];return `<button class="category-pill ${activeCategory===key?"active":""}" data-category="${escapeHtml(key)}">${escapeHtml(label)}</button>`;}).join("");box.querySelectorAll("button").forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;renderPills();renderProducts();});}
function renderProducts(){const query=document.getElementById("productSearch").value.trim().toLowerCase();const list=getProducts().filter(p=>p.category===activeMetal&&matchesCategory(p)&&(!query||[p.name,p.category,p.type,p.description].join(" ").toLowerCase().includes(query)));const grid=document.getElementById("productGrid");grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image-wrap"><img class="product-image" src="${escapeHtml(p.image||"https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=85")}" alt="${escapeHtml(p.name)}" loading="lazy"><span class="product-tag">${p.category==="gold"?"GOLD":"SILVER"} · ${escapeHtml(p.type||"JEWELLERY")}</span>${p.stock==="Out of Stock"?'<span class="stock-tag">OUT OF STOCK</span>':""}</div><div class="product-body"><div class="product-category">${escapeHtml(p.category)} jewellery</div><h3>${escapeHtml(p.name)}</h3><div class="product-meta"><span>${escapeHtml(p.weight||"Weight on request")}</span><span>HUID ${escapeHtml(p.huid||"Please enquire")}</span><span>Custom ${escapeHtml(p.customisation||"Please enquire")}</span></div><div class="product-price">${p.price?escapeHtml(p.price):"Price on Request"}</div><div class="product-actions"><button data-view="${p.id}">View Details</button><button data-order="${p.id}" ${p.stock==="Out of Stock"?"disabled":""}>${p.stock==="Out of Stock"?"Out of Stock":"Order on WhatsApp"}</button></div></div></article>`).join("");document.getElementById("emptyState").hidden=!!list.length;grid.hidden=!list.length;grid.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>openProduct(b.dataset.view));grid.querySelectorAll("[data-order]").forEach(b=>b.onclick=()=>{const p=getProducts().find(x=>String(x.id)===b.dataset.order);if(p&&p.stock!=="Out of Stock"){recordEnquiry(p.name);window.open(whatsappLink(orderMessage(p)),"_blank","noopener");}});}
function openProduct(id){const p=getProducts().find(x=>String(x.id)===String(id));if(!p)return;const c=document.getElementById("modalContent");c.innerHTML=`<div class="modal-layout"><img src="${escapeHtml(p.image||"")}" alt="${escapeHtml(p.name)}"><div class="modal-info"><div class="product-category">${escapeHtml(p.category)} jewellery · ${escapeHtml(p.type||"")}</div><h2>${escapeHtml(p.name)}</h2><p>${escapeHtml(p.description||"A beautiful piece from Jyothirmaye Jewellers. Please contact our team for further details.")}</p><div class="modal-details"><div><small>WEIGHT</small><b>${escapeHtml(p.weight||"On request")}</b></div><div><small>HUID STATUS</small><b>${escapeHtml(p.huid||"Please enquire")}</b></div><div><small>CUSTOMISATION</small><b>${escapeHtml(p.customisation||"Please enquire")}</b></div><div><small>AVAILABILITY</small><b>${escapeHtml(p.stock||"Available")}</b></div></div><div class="product-price">${p.price?escapeHtml(p.price):"Price on Request"}</div><div class="modal-buttons"><button class="btn btn-dark" id="modalOrder" ${p.stock==="Out of Stock"?"disabled":""}>${p.stock==="Out of Stock"?"Out of Stock":"Order on WhatsApp ↗"}</button><button class="btn btn-gold" data-close-modal>Close</button></div></div></div>`;document.getElementById("productModal").showModal();const o=document.getElementById("modalOrder");if(!o.disabled)o.onclick=()=>{recordEnquiry(p.name);window.open(whatsappLink(orderMessage(p)),"_blank","noopener");};c.querySelectorAll("[data-close-modal]").forEach(x=>x.onclick=()=>document.getElementById("productModal").close());}
function updateSettings(){const s=getSettings();const set=(id,val,fall)=>document.getElementById(id).textContent=val||fall;document.getElementById("shopAddress").innerHTML=escapeHtml(s.address||SHOP_ADDRESS).replace(/,\s*/g,",<br>");set("shopPhone",s.phone,"09440030500");set("shopWhatsapp","09440030500","09440030500");document.getElementById("shopPhoneLink").href="tel:"+(s.phone||"09440030500");document.getElementById("shopWhatsappLink").href="https://wa.me/"+waNumber();document.getElementById("footerAddress").innerHTML=escapeHtml(s.address||SHOP_ADDRESS).replace(/,\s*/g,",<br>");document.getElementById("footerPhone").href="tel:"+(s.phone||"09440030500");document.getElementById("footerPhone").textContent=s.phone||"09440030500";document.getElementById("footerWhatsapp").href="https://wa.me/"+waNumber();document.getElementById("footerWhatsapp").textContent="09440030500";set("shopEmail",s.email,"Add email address");document.getElementById("goldRate").textContent=s.goldRate?"INR "+s.goldRate:"Set rate in Admin Settings";document.getElementById("silverRate").textContent=s.silverRate?"INR "+s.silverRate:"Set rate in Admin Settings";if(s.shopName){document.querySelectorAll(".brand-name").forEach(el=>{el.innerHTML=`${escapeHtml(s.shopName.toUpperCase().replace(" JEWELLERS",""))}<small>JEWELLERS</small>`;});document.title=`${s.shopName} | Gold & Silver Since 1990`;}const phone=String(s.phone||"").replace(/[^\d+]/g,"");document.getElementById("callButton").href=phone?`tel:${phone}`:"#";document.querySelectorAll("[data-whatsapp]").forEach(a=>a.href=whatsappLink(`Hello ${s.shopName||"Jyothirmaye Jewellers"}, I would love to know more about your jewellery collections. Thank you.`));const savedMap=s.mapsUrl&&!s.mapsUrl.includes("6zsCay4DdAY8d2nu7")?s.mapsUrl:SHOP_MAP_URL;document.getElementById("directionsLink").href=savedMap;const frame=document.getElementById("mapFrame");if(savedMap.includes("output=embed")||savedMap.includes("google.com/maps/embed"))frame.src=savedMap;else frame.src=`https://maps.google.com/maps?q=${encodeURIComponent(s.address||SHOP_ADDRESS)}&z=18&output=embed`;document.querySelectorAll("[data-social]").forEach(a=>{const key={instagram:"instagram",facebook:"facebook",youtube:"youtube"}[a.dataset.social];if(s[key])a.href=s[key];});}
function showToast(message){const t=document.getElementById("toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400);}
function init(){renderPills();renderProducts();updateSettings();document.querySelectorAll(".metal-switch button").forEach(b=>b.onclick=()=>{activeMetal=b.dataset.metal;activeCategory="All";document.querySelectorAll(".metal-switch button").forEach(x=>x.classList.toggle("active",x===b));renderPills();renderProducts();});document.getElementById("productSearch").addEventListener("input",renderProducts);document.querySelectorAll("[data-metal-link]").forEach(a=>a.addEventListener("click",()=>{activeMetal=a.dataset.metalLink;activeCategory="All";document.querySelectorAll(".metal-switch button").forEach(x=>x.classList.toggle("active",x.dataset.metal===activeMetal));renderPills();renderProducts();}));document.getElementById("searchTrigger").onclick=()=>{document.getElementById("productSearch").focus();document.getElementById("products").scrollIntoView({behavior:"smooth"});};document.getElementById("customRequest").onclick=()=>{recordEnquiry("Custom gold jewellery request");window.open(whatsappLink("Hello Jyothirmaye Jewellers,\n\nI would like to customise a gold jewellery design.\n\nDesign details:\n\n---\n\nPreferred weight:\n\n---\n\nAdditional requirements:\n\n---\n\nPlease contact me."),"_blank","noopener");};document.querySelectorAll("[data-whatsapp]").forEach(a=>a.addEventListener("click",()=>recordEnquiry("General jewellery enquiry")));const nav=document.getElementById("mainNav"),toggle=document.getElementById("menuToggle");toggle.onclick=()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",open);};nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");toggle.setAttribute("aria-expanded","false");}));document.querySelectorAll("[data-collection]").forEach(a=>a.onclick=()=>{const val=a.dataset.collection.toLowerCase();document.getElementById("productSearch").value=val;activeCategory="All";renderPills();renderProducts();});document.getElementById("backTop").onclick=()=>window.scrollTo({top:0,behavior:"smooth"});window.addEventListener("scroll",()=>document.getElementById("backTop").classList.toggle("visible",window.scrollY>450));document.getElementById("productModal").addEventListener("click",e=>{if(e.target.id==="productModal")e.currentTarget.close();});document.addEventListener("keydown",e=>{if(e.key==="Escape")document.getElementById("productModal").close();if(e.key==="/"&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName)){e.preventDefault();document.getElementById("productSearch").focus();}});window.addEventListener("storage",e=>{if(e.key===PRODUCT_KEY){renderProducts();}if(e.key===SETTINGS_KEY)updateSettings();});const observer=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add("in-view");observer.unobserve(x.target);}}),{threshold:.12});document.querySelectorAll(".trust-strip article,.product-card,.collection-card,.custom-copy,.about-copy,.visit-grid").forEach(el=>observer.observe(el));}
document.addEventListener("DOMContentLoaded",init);
